### PR TITLE
ci: GitHub Actions inline unit test report

### PR DESCRIPTION
**Pull request by apparition47**
Inline CI Xcode test reports

Sample: https://github.com/apparition47/macos-push-tester/runs/4010115076?check_suite_focus=true

### CODE REVIEW

**Comment by malayli** [comment]
@apparition47 Is this PR ready to be reviewed? or is still a draft?

**Comment by apparition47** [comment]
Still a draft. Wanted to add Bitrise Test Reports too

**Comment by malayli** [comment]
@apparition47 Do you need a JIRA ticket to complete this task?

**Comment by malayli** [comment]
@apparition47 Do you think we can merge this PR and add Bitrise Tests report in an other PR?

**Pull request merged**
