### PR TITLE
Preview update

### PR DESCRIPTION
**Pull request by malayli**

### CODE REVIEW

**Review by apparition47 — APPROVED** [review]
Could make the screenshot sizes smaller without the shadow. NBD.

**Comment by malayli** [comment]
> Could make the screenshot sizes smaller without the shadow. NBD.

Is there an easy way to remove the shadow?

**Comment by apparition47** [comment]
It's a [screencapture setting](https://www.macworld.com/article/233847/how-to-get-rid-of-the-screenshot-drop-shadow-in-macos.html)

**Comment by imaginaris** [comment]
> Could make the screenshot sizes smaller without the shadow. NBD.

Converting to JPEG (or modify screen capture setting to save in JPEG) will also drastically reduce the size but it will remove alpha channel so it's better to remove the shadow anyway

**Comment by malayli** [comment]
> It's a [screencapture setting](https://www.macworld.com/article/233847/how-to-get-rid-of-the-screenshot-drop-shadow-in-macos.html)

Ok I only needed to hold down the Option key while clicking. Thanks.

**Comment by malayli** [comment]
> > Could make the screenshot sizes smaller without the shadow. NBD.
> 
> Converting to JPEG (or modify screen capture setting to save in JPEG) will also drastically reduce the size but it will remove alpha channel so it's better to remove the shadow anyway

@imaginaris If I convert the images to JPEG, then the transparency will be replaced by a white color (in the corners):
Screenshot 2021-11-19 at 12 03 02
:

**Comment by imaginaris** [comment]
> > > Could make the screenshot sizes smaller without the shadow. NBD.
> > 
> > 
> > Converting to JPEG (or modify screen capture setting to save in JPEG) will also drastically reduce the size but it will remove alpha channel so it's better to remove the shadow anyway
> 
> @imaginaris If I convert the images to JPEG, then the transparency will be replaced by a white color (in the corners): Screenshot 2021-11-19 at 12 03 02 :

Ah corners... Ok let's stay with PNG 
(...or maybe JPEG2000 😜 )

**Pull request merged**
